#!/bin/sh

NumMonitors=$(xrandr -q | grep ' connected' | wc -l)
if [ $NumMonitors = "1" ]; then
    xrandr --output eDP1 --auto --output HDMI2 --off
else
    xrandr --output eDP1 --off --output HDMI2 --auto
fi
